### ISSUE TITLE
Allow indices as part of a path?

### ISSUE THREAD

**Issue by abr-egn** [bheisler/TinyTemplate#10]
It looks like path traversal currently uses serde_json::Value::get, which supports both string keys for maps and numeric keys for arrays.  However, TinyTemplate only invokes the string lookup, so any lookup on an array will fail; this is particularly a hassle for tuples, which serde_json::Value represents as arrays.

This can be fixed by attempting to parse the path element as a usize and using that for value lookup if name lookup fails; doing it only on name lookup failure means that any situations where a map is being constructed with string keys that happen to be parseable as usize will continue to work.

I have a PR ready if this approach sounds reasonable :)

**Comment by BrettMayson** [comment]
Status? @abr-egn Can you create the PR?
