### ISSUE TITLE
Example does not compile

### ISSUE THREAD

**Issue by mqus** [bheisler/TinyTemplate#11]
Thank you for your crate!
I tried to use it and cargo/rustc didn't seem to find the `Serialize` trait. I then tried to copy your example in the README.md and it also failed to compile (i did add the dependencies you mentioned):
```
   Updating crates.io index
   Compiling proc-macro2 v1.0.18
   Compiling ryu v1.0.5
   Compiling serde v1.0.114
   Compiling unicode-xid v0.2.1
   Compiling syn v1.0.33
   Compiling serde_json v1.0.56
   Compiling itoa v0.4.6
   Compiling serde_derive v1.0.114
   Compiling quote v1.0.7
   Compiling tinytemplate v1.1.0
   Compiling tttest v0.1.0 (/tmp/tttest)
error[E0463]: can't find crate for `serde`
 --> src/main.rs:8:10
  |
8 | #[derive(Serialize)]
  |          ^^^^^^^^^ can't find crate
  |
  = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: could not compile `tttest`.

To learn more, run the command again with --verbose.
```
I assume that `serde_derive` does not contain the Traits necessary to compile this, so instead of depending on `serde_derive`, the README should use `serde = { version = "1.0", features = ["derive"] }`, as written in [serdes documentation](https://serde.rs/derive.html). It then follows that the example code should use
```rust
use serde::Serialize;
```
instead of 
```rust
#[macro_use]
extern crate serde_derive;
```

**Comment by nickhallph** [comment]
I am running into this issue as well, and would love resolution on this! :blush:

**Comment by nickhallph** [comment]
In *`/Cargo.toml`*:

`serde = { version = "1.0", features = ["derive"] }`

as stated in @mqus's issue was the solution I needed to remove this error!
