### ISSUE TITLE
Allow changing special characters, from braces to something else

### ISSUE THREAD

**Issue by Mazwak** [bheisler/TinyTemplate#13]
Hello

I tried to use tinytemplate to create powershell script.

However, unlike HTML, ps scripts use braces everywhere.

Do you think it would be possible to add a way to change to another pair ?

regards

**Comment by bheisler** [comment]
Hi, thanks for the suggestion, and thanks for the patience.

I'm sorry to say I don't think that's a feature I want to add. TinyTemplate is deliberately minimal, and part of that is that it doesn't allow for much configuration. Indeed, extensibility is a definite non-goal.

I would encourage you to check out the one of the other templating crates available for Rust (though I'm sure that in the past ~four months you've already done so).
