### ISSUE TITLE
different syntax for variables

### ISSUE THREAD

**Issue by mimoo** [bheisler/TinyTemplate#29]
right now I'm using

```
{ thing }
```

to print a variable, but this is colliding with LaTeX blocks in my text. Is it possible to change that to something like

```
<[ thing ]>
```

**Comment by bheisler** [comment]
Hello!

I'm afraid not. Overriding the template syntax is one of the features TinyTemplate deliberately does not have in order to continue being tiny. Perhaps another template library would be a better fit for your needs.
