### ISSUE TITLE
Is it possible to change the default formater?

### ISSUE THREAD

**Issue by d4h0** [bheisler/TinyTemplate#8]
Hi,

TinyTemplate looks ideal for a use-case I have.

The problem is, that I will not generate HTML, so the default formatter that does HTML escaping is a big problem for me (I don't want to add " | unescaped" to every value usage).

Is there a way to change the default formatter?

I looked at the source code and it seems this is not possible. But I'm a Rust beginner, so maybe I'm missing something.

**Comment by bheisler** [comment]
This is not currently supported, no. It probably wouldn't be too hard to add though, and I suppose the extra flexibility is probably worth the complexity cost of adding one extra setting.

**Comment by d4h0** [comment]
With the merged PR above, I think this can be closed
